### PR TITLE
Add more custom format specifiers

### PR DESCRIPTION
**Pull request by merlinz01**
Add `{x0}` through `{x10}` custom format specifiers to enable finer format customizations.
Also add a `{nl}` specifier to insert a newline for multiline formats.

Example custom format:
`// __NAME__ {B}{nl}const __NAME__: GUID = GUID {data1: 0x{x0}, data2: 0x{x1}, data3: 0x{x2}, data4: [0x{x3}, 0x{x4}, 0x{x5}, 0x{x6}, 0x{x7}, 0x{x8}, 0x{x9}, 0x{x10}]};`

Result:
```rust
// __NAME__ {C6156C70-C766-4962-AFF1-30C56AAAA892}
const __NAME__: GUID = GUID {data1: 0xc6156c70, data2: 0xc766, data3: 0x4962, data4: [0xaf, 0xf1, 0x30, 0xc5, 0x6a, 0xaa, 0xa8, 0x92]};
```

### CODE REVIEW

**Review by heaths — CHANGES_REQUESTED** [review]
Thanks! This is great. Could you add some tests for `guid.ts` changes, though? I'll make a few adjustments to the docs - I should've documented that better in the `README.md` when those changes were added - but will then go ahead and merge this.

**Comment by merlinz01** [comment]
I added tests, see [this commit](https://github.com/heaths/vscode-guid/pull/85/commits/186450946f0982c81d23d042117e17dfe33a084c).

**Review by heaths — APPROVED** [review]
Thank you! I'm going to clean up docs a little - something I should've done before - and get this merged.

**Comment by heaths** [comment]
[v1.9.0](https://marketplace.visualstudio.com/items?itemName=heaths.vscode-guid) with this change has been released. Thank you again!

**Pull request merged**
